export const WAVE_SIZES = [
  5,
  6,
  7,
  9,
  11,
  12,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  15,
  15,
  15,
];

export const WAVE_TYPES = {
  BASIC: 'BASIC',
  BOMBER: 'BOMBER',
  BOSS: 'BOSS',
};

export const WAVES = [
  // Debug wave
  // { type: 'BASIC', count: 1 },
  { type: WAVE_TYPES.BASIC, count: 3 },
  { type: WAVE_TYPES.BOSS, count: 1 },
  { type: WAVE_TYPES.BASIC, count: 6 },
  { type: WAVE_TYPES.BASIC, count: 7 },
  { type: WAVE_TYPES.BASIC, count: 9 },
  { type: WAVE_TYPES.BOSS, count: 2 },
  { type: WAVE_TYPES.BASIC, count: 11 },
  { type: WAVE_TYPES.BASIC, count: 11 },
  { type: WAVE_TYPES.BASIC, count: 12 },
  { type: WAVE_TYPES.BASIC, count: 13 },
  { type: WAVE_TYPES.BASIC, count: 13 },
  { type: WAVE_TYPES.BASIC, count: 13 },
  { type: WAVE_TYPES.BASIC, count: 13 },
  { type: WAVE_TYPES.BASIC, count: 13 },
  { type: WAVE_TYPES.BASIC, count: 13 },
  { type: WAVE_TYPES.BASIC, count: 15 },
  { type: WAVE_TYPES.BASIC, count: 15 },
  { type: WAVE_TYPES.BASIC, count: 15 },
  { type: WAVE_TYPES.BASIC, count: 15 },
  { type: WAVE_TYPES.BASIC, count: 15 },
];
